### ISSUE TITLE
./install doesn't work

### ISSUE THREAD

**Issue by jeremyb31** [Schallaven/kittykernel#1]
It looks to be more of an uninstall file with all the sudo rm -r commands

It works fine in Linux Mint, Ubuntu 16.04 didn't like it
Is it possible to show just generic kernels and hide the low latency ones
Ubuntu just needed python3-setproctitle installed

**Comment by Schallaven** [comment]
It is easier to install the debian package, which will check for all required packages (under releases).

I updated the install script a little bit; the rm commands are just for removing a previous installation of kittykernel. It now checks if it is present (at least /usr/lib/kittykernel). Also, I added some comments to make it clear was the script does.

Filter options like this are planned, but not implemented yet :) 

Thanks for your feedback!

**Comment by Schallaven** [comment]
The [new release](https://github.com/Schallaven/kittykernel/releases/tag/v1.1) features a blacklist :)
